verbose = true

[env]
SMARTSHEET_ACCESS_TOKEN = "8MFPRT7WqCkwCCZQxbfiiZxaHpCbY6ieostvu"
target_workspace = "1468693428593860"
target_folder = "4162732984672044"

[tables.EFFECTIVITY_REPORT_STANDARD_A320_20250115_419]
id = ""
src = "EFFECTIVITY_REPORT_STANDARD_A320_20250115_419.xlsx"


